---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: Install Apache2 Server
    apt:
      name: apache2
      state: latest

  - name: Add php support for apache2
    apt:
      name: libapache2-mod-php
      state: latest
