---
- hosts: all
  become: true
  tasks:
 
  - name: install apache and php for Ubuntu servers
    tags: ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - mariadb-server
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
   

  - name: install apache and php for CentOS servers
    tags: centos
    dnf:
      name:
        - httpd
        - php
        - mariadb-server
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
 
  - name: Install samba
    package: 
      name: samba
      state: latest

  - name: copy default html file for file
    tags: apache,apche2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
